spring.application.name=SecondHW

#spring.datasource.url=jdbc:postgresql://localhost:5435/postgres
spring.datasource.url=jdbc:postgresql://database:5432/secondhw
spring.datasource.username=postgres
spring.datasource.password=password

#
#spring.datasource.url=jdbc:postgresql://localhost:5435/secondhw
#spring.datasource.username=root
#spring.datasource.password=password


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
server.port=8080